## การจัดเตรียมข้อมูลเพื่อใช้ในการฝึกสอน(Train) และการทดสอบ(Test)

1. นำเข้า Library ที่จำเป็นในการจัดเตรียมข้อมูล
2. ทดลองสร้างข้อมูลสำหรับ X (ข้อมูลเข้า (Input/Features)) และ y (ข้อมูลผลเฉลย (Output / Target / Label))
3. ทำการสุ่ม(Random) เพื่อแยกข้อมูล(Split) สำหรับการฝึกสอน(Train) และการทดสอบ(Test)



In [1]:
import numpy as np
from sklearn.model_selection import train_test_split  # นำเข้า Library ที่จำเป็นในการจัดเตรียมข้อมูล: sklearn.model_selection

X, y = np.arange(10).reshape((5,2)), range(5)         # ทดลองสร้างข้อมูลสำหรับ X (ข้อมูลเข้า (Input/Features)) และ y (ข้อมูลผลเฉลย (Output / Target / Label))

In [2]:
# แสดงข้อมูล X (ข้อมูลเข้า (Input/Features)): X
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [3]:
# แสดงข้อมูล y (ข้อมูลผลเฉลย (Output / Target / Label)): y
y

range(0, 5)

In [4]:
# ทำการสุ่ม(Random) เพื่อแยกข้อมูล(Split) สำหรับการฝึกสอน(Train) และการทดสอบ(Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.33, random_state=42)  # กำหนดให้แบ่งข้อมูล เพื่อใช้ทดสอบ 33%: X, y, 0.33, 42

In [5]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [6]:
y_train

[2, 0, 3]

In [7]:
X_test

array([[2, 3],
       [8, 9]])

In [8]:
y_test

[1, 4]

## ถ้าต้องการเตรียมข้อมูล โดยเรียงลำดับข้อมูลจากซ้ายไปขวา(ไม่มีการสุ่ม)
ให้ระบุ train_test_split(...) โดยเพิ่ม Parameter ที่ชื่อว่า shuffle=False

In [9]:
train_test_split(y, shuffle=False)

[[0, 1, 2], [3, 4]]

In [10]:
train_test_split(X, shuffle=False)

[array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[6, 7],
        [8, 9]])]